"""
phylogenetic_analysis.py

Utilities for validating and summarizing TP53 phylogenetic
analysis outputs generated by the phylogenetic workflow.

The actual maximum-likelihood tree reconstruction is performed
using IQ-TREE. This Python script provides repository-level
validation and metadata extraction.

Author
------
Ritika Rajendra Rawat
"""

from pathlib import Path


TREE_FILE = Path(
    "results/phylogeny/TP53_mammals.treefile"
)

IQTREE_REPORT = Path(
    "results/phylogeny/TP53_mammals.iqtree"
)


def validate_files():

    missing = []

    for path in [
        TREE_FILE,
        IQTREE_REPORT,
    ]:

        if not path.exists():
            missing.append(str(path))

    if missing:

        raise FileNotFoundError(
            "Missing phylogenetic outputs:\n"
            + "\n".join(missing)
        )


def summarize_tree():

    with open(
        TREE_FILE,
        "r",
        encoding="utf-8"
    ) as handle:

        tree = handle.read().strip()

    print(
        "Phylogenetic tree successfully loaded."
    )

    print(
        f"Tree characters: {len(tree)}"
    )

    print(
        f"Tree starts with: {tree[:100]}"
    )


def main():

    validate_files()

    summarize_tree()

    print(
        "\nPhylogenetic output validation completed."
    )

    print(
        "Maximum-likelihood reconstruction should "
        "be performed using the documented IQ-TREE workflow."
    )


if __name__ == "__main__":
    main()
