# -*- coding: utf-8 -*-
"""TP53_Evolutionary_Functional_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4Wvch7dNmwyeZ09_imJVJy2lwrPc6Th
"""

!pip -q install biopython pandas numpy scipy matplotlib
!apt-get -qq install clustalo

from Bio import AlignIO
from collections import Counter
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu
from google.colab import files

uploaded = files.upload()

!clustalo -i TP53_multispecies.fasta -o TP53_MSA.fasta --force --outfmt fasta

!ls

alignment = AlignIO.read("TP53_MSA.fasta", "fasta")

print("Sequences:", len(alignment))
print("Alignment length:", alignment.get_alignment_length())

def conservation_score(column):
    counts = Counter(column.replace("-", ""))
    if not counts:
        return 0
    return max(counts.values()) / sum(counts.values())

scores = []
for i in range(alignment.get_alignment_length()):
    col = alignment[:, i]
    scores.append(conservation_score(col))

hotspots = [175, 245, 248, 249, 273, 282]

hotspot_scores = [scores[pos-1] for pos in hotspots]

non_hotspots = [i for i in range(len(scores)) if (i+1) not in hotspots]

np.random.seed(42)
sample_non = np.random.choice(non_hotspots, size=30, replace=False)
non_scores = [scores[i] for i in sample_non]

stat, p = mannwhitneyu(hotspot_scores, non_scores)

print("Hotspot mean:", np.mean(hotspot_scores))
print("Non-hotspot mean:", np.mean(non_scores))
print("p-value:", p)

plt.figure(figsize=(6,5))
plt.boxplot([hotspot_scores, non_scores])
plt.xticks([1,2], ["Hotspots", "Non-hotspots"])
plt.ylabel("Conservation Score")
plt.title("TP53 Conservation Comparison")

plt.savefig("Figure1_Boxplot.png", dpi=300)
plt.show()

from Bio.Align import substitution_matrices
blosum62 = substitution_matrices.load("BLOSUM62")

def mutation_impact_score(wt, mut):
    if (wt, mut) in blosum62:
        return blosum62[(wt, mut)]
    elif (mut, wt) in blosum62:
        return blosum62[(mut, wt)]
    else:
        return -4

reference_seq = alignment[0].seq  # assume first = human

impact_scores = []

for pos in hotspots:
    col = alignment[:, pos-1]
    wt = reference_seq[pos-1]

    scores_mut = []
    for aa in col:
        if aa != wt and aa != '-':
            scores_mut.append(mutation_impact_score(wt, aa))

    impact_scores.append(np.mean(scores_mut) if scores_mut else 0)

df = pd.DataFrame({
    "Position": hotspots,
    "Conservation": hotspot_scores,
    "BLOSUM62_Impact": impact_scores
})

print(df)

plt.figure(figsize=(6,5))
plt.scatter(df["Conservation"], df["BLOSUM62_Impact"])
plt.xlabel("Conservation Score")
plt.ylabel("BLOSUM62 Impact")
plt.title("Impact vs Conservation")

plt.savefig("Figure2_Scatter.png", dpi=300)
plt.show()

df.to_csv("TP53_hotspot_analysis.csv", index=False)

files.download("TP53_MSA.fasta")
files.download("TP53_hotspot_analysis.csv")
files.download("Figure1_Boxplot.png")
files.download("Figure2_Scatter.png")